<?php

/**
 * This is the model base class for the table "cleaning_cars".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CleaningCars".
 *
 * Columns in table "cleaning_cars" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $number_plate
 * @property string $car_make
 * @property string $car_model
 * @property string $car_color
 * @property string $base_city
 * @property string $leasing_company
 * @property string $lease_expires_on
 * @property string $remarks
 * @property string $extra
 *
 */
abstract class BaseCleaningCars extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'cleaning_cars';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CleaningCars|CleaningCars', $n);
	}

	public static function representingColumn() {
		return 'number_plate';
	}

	public function rules() {
		return array(
			array('number_plate, car_make, car_model, car_color, base_city', 'required'),
			array('number_plate, car_color', 'length', 'max'=>32),
			array('car_make, car_model, base_city, leasing_company, extra', 'length', 'max'=>128),
			array('remarks', 'length', 'max'=>512),
			array('lease_expires_on', 'safe'),
			array('leasing_company, lease_expires_on, remarks, extra', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, number_plate, car_make, car_model, car_color, base_city, leasing_company, lease_expires_on, remarks, extra', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'number_plate' => Yii::t('app', 'Number Plate'),
			'car_make' => Yii::t('app', 'Car Make'),
			'car_model' => Yii::t('app', 'Car Model'),
			'car_color' => Yii::t('app', 'Car Color'),
			'base_city' => Yii::t('app', 'Base City'),
			'leasing_company' => Yii::t('app', 'Leasing Company'),
			'lease_expires_on' => Yii::t('app', 'Lease Expires On'),
			'remarks' => Yii::t('app', 'Remarks'),
			'extra' => Yii::t('app', 'Extra'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('number_plate', $this->number_plate, true);
		$criteria->compare('car_make', $this->car_make, true);
		$criteria->compare('car_model', $this->car_model, true);
		$criteria->compare('car_color', $this->car_color, true);
		$criteria->compare('base_city', $this->base_city, true);
		$criteria->compare('leasing_company', $this->leasing_company, true);
		$criteria->compare('lease_expires_on', $this->lease_expires_on, true);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('extra', $this->extra, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}