<?php

/**
 * This is the model base class for the table "employees".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Employees".
 *
 * Columns in table "employees" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $emp_num
 * @property string $emp_name
 * @property string $emp_init
 * @property string $emp_last_name
 * @property string $emp_gender
 * @property string $emp_phone_no
 * @property string $emp_email
 * @property string $emp_driving_license
 * @property string $emp_base_location
 * @property integer $emp_working_days
 * @property string $emp_work_hr_begin
 * @property string $emp_work_hr_end
 * @property string $emp_designation
 * @property string $emp_contract_end_date
 * @property string $remarks
 * @property string $emp_ex1
 * @property integer $sunday
 * @property integer $monday
 * @property integer $tuesday
 * @property integer $wednesday
 * @property integer $thursday
 * @property integer $friday
 * @property integer $saturday
 *
 */
abstract class BaseEmployees extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'employees';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Employees|Employees', $n);
	}

	public static function representingColumn() {
		return 'emp_name';
	}

	public function rules() {
		return array(
			array('emp_num, emp_name, emp_init, emp_last_name, emp_gender, emp_phone_no, emp_driving_license, emp_base_location, emp_work_hr_begin, emp_work_hr_end, emp_designation, emp_contract_end_date', 'required'),
			array('emp_num, emp_working_days, sunday, monday, tuesday, wednesday, thursday, friday, saturday', 'numerical', 'integerOnly'=>true),
			array('emp_name, emp_last_name, emp_email, emp_driving_license, emp_base_location, emp_ex1', 'length', 'max'=>128),
			array('emp_init, emp_phone_no', 'length', 'max'=>32),
			array('emp_gender', 'length', 'max'=>6),
			array('emp_designation', 'length', 'max'=>16),
			array('remarks', 'length', 'max'=>512),
			array('emp_email, emp_working_days, remarks, emp_ex1, sunday, monday, tuesday, wednesday, thursday, friday, saturday', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, emp_num, emp_name, emp_init, emp_last_name, emp_gender, emp_phone_no, emp_email, emp_driving_license, emp_base_location, emp_working_days, emp_work_hr_begin, emp_work_hr_end, emp_designation, emp_contract_end_date, remarks, emp_ex1, sunday, monday, tuesday, wednesday, thursday, friday, saturday', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'emp_num' => Yii::t('app', 'Emp Num'),
			'emp_name' => Yii::t('app', 'Emp Name'),
			'emp_init' => Yii::t('app', 'Emp Init'),
			'emp_last_name' => Yii::t('app', 'Emp Last Name'),
			'emp_gender' => Yii::t('app', 'Emp Gender'),
			'emp_phone_no' => Yii::t('app', 'Emp Phone No'),
			'emp_email' => Yii::t('app', 'Emp Email'),
			'emp_driving_license' => Yii::t('app', 'Emp Driving License'),
			'emp_base_location' => Yii::t('app', 'Emp Base Location'),
			'emp_working_days' => Yii::t('app', 'Emp Working Days'),
			'emp_work_hr_begin' => Yii::t('app', 'Emp Work Hr Begin'),
			'emp_work_hr_end' => Yii::t('app', 'Emp Work Hr End'),
			'emp_designation' => Yii::t('app', 'Emp Designation'),
			'emp_contract_end_date' => Yii::t('app', 'Emp Contract End Date'),
			'remarks' => Yii::t('app', 'Remarks'),
			'emp_ex1' => Yii::t('app', 'Emp Ex1'),
			'sunday' => Yii::t('app', 'Sunday'),
			'monday' => Yii::t('app', 'Monday'),
			'tuesday' => Yii::t('app', 'Tuesday'),
			'wednesday' => Yii::t('app', 'Wednesday'),
			'thursday' => Yii::t('app', 'Thursday'),
			'friday' => Yii::t('app', 'Friday'),
			'saturday' => Yii::t('app', 'Saturday'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('emp_num', $this->emp_num);
		$criteria->compare('emp_name', $this->emp_name, true);
		$criteria->compare('emp_init', $this->emp_init, true);
		$criteria->compare('emp_last_name', $this->emp_last_name, true);
		$criteria->compare('emp_gender', $this->emp_gender, true);
		$criteria->compare('emp_phone_no', $this->emp_phone_no, true);
		$criteria->compare('emp_email', $this->emp_email, true);
		$criteria->compare('emp_driving_license', $this->emp_driving_license, true);
		$criteria->compare('emp_base_location', $this->emp_base_location, true);
		$criteria->compare('emp_working_days', $this->emp_working_days);
		$criteria->compare('emp_work_hr_begin', $this->emp_work_hr_begin, true);
		$criteria->compare('emp_work_hr_end', $this->emp_work_hr_end, true);
		$criteria->compare('emp_designation', $this->emp_designation, true);
		$criteria->compare('emp_contract_end_date', $this->emp_contract_end_date, true);
		$criteria->compare('remarks', $this->remarks, true);
		$criteria->compare('emp_ex1', $this->emp_ex1, true);
		$criteria->compare('sunday', $this->sunday);
		$criteria->compare('monday', $this->monday);
		$criteria->compare('tuesday', $this->tuesday);
		$criteria->compare('wednesday', $this->wednesday);
		$criteria->compare('thursday', $this->thursday);
		$criteria->compare('friday', $this->friday);
		$criteria->compare('saturday', $this->saturday);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	public function getFullName(){
			return $this->emp_name.' '.$this->emp_init.' '.$this->emp_last_name;
	}
}