<?php

/**
 * This is the model base class for the table "plans".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Plans".
 *
 * Columns in table "plans" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $plan_name
 * @property double $plan_cost
 * @property integer $plan_duration
 * @property integer $plan_freq
 * @property string $remarks
 *
 */
abstract class BasePlans extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plans';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Plans|Plans', $n);
	}

	public static function representingColumn() {
		return 'plan_name';
	}

	public function rules() {
		return array(
			array('plan_name, plan_cost, plan_duration, plan_freq, remarks', 'required'),
			array('plan_duration, plan_freq', 'numerical', 'integerOnly'=>true),
			array('plan_cost', 'numerical'),
			array('plan_name, remarks', 'length', 'max'=>128),
			array('id, plan_name, plan_cost, plan_duration, plan_freq, remarks', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'plan_name' => Yii::t('app', 'Plan Name'),
			'plan_cost' => Yii::t('app', 'Plan Cost'),
			'plan_duration' => Yii::t('app', 'Plan Duration'),
			'plan_freq' => Yii::t('app', 'Plan Freq'),
			'remarks' => Yii::t('app', 'Remarks'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('plan_name', $this->plan_name, true);
		$criteria->compare('plan_cost', $this->plan_cost);
		$criteria->compare('plan_duration', $this->plan_duration);
		$criteria->compare('plan_freq', $this->plan_freq);
		$criteria->compare('remarks', $this->remarks, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}