<?php

/**
 * This is the model base class for the table "company_master_locations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompanyMasterLocations".
 *
 * Columns in table "company_master_locations" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $company_id
 * @property string $company_name
 * @property integer $location_id
 * @property string $location_address
 * @property string $location_city
 * @property string $location_zipcode
 * @property string $remarks
 *
 */
abstract class BaseCompanyMasterLocations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'company_master_locations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CompanyMasterLocations|CompanyMasterLocations', $n);
	}

	public static function representingColumn() {
		return 'company_name';
	}

	public function rules() {
		return array(
			array('company_name, location_address, location_city, location_zipcode', 'required'),
			array('company_id, location_id', 'numerical', 'integerOnly'=>true),
			array('company_name', 'length', 'max'=>128),
			array('location_address, location_city', 'length', 'max'=>256),
			array('location_zipcode', 'length', 'max'=>32),
			array('remarks', 'length', 'max'=>512),
			array('company_id, location_id, remarks', 'default', 'setOnEmpty' => true, 'value' => null),
			array('company_id, company_name, location_id, location_address, location_city, location_zipcode, remarks', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'company_id' => Yii::t('app', 'Company'),
			'company_name' => Yii::t('app', 'Company Name'),
			'location_id' => Yii::t('app', 'Location'),
			'location_address' => Yii::t('app', 'Location Address'),
			'location_city' => Yii::t('app', 'Location City'),
			'location_zipcode' => Yii::t('app', 'Location Zipcode'),
			'remarks' => Yii::t('app', 'Remarks'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('company_id', $this->company_id);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('location_address', $this->location_address, true);
		$criteria->compare('location_city', $this->location_city, true);
		$criteria->compare('location_zipcode', $this->location_zipcode, true);
		$criteria->compare('remarks', $this->remarks, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}