<?php

/**
 * This is the model base class for the table "invites".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Invites".
 *
 * Columns in table "invites" available as properties of the model,
 * followed by relations of table "invites" available as properties of the model.
 *
 * @property integer $id
 * @property string $cre_date
 * @property integer $company_id
 * @property string $username
 * @property string $lastname
 * @property string $email
 * @property string $invite_key
 * @property string $remarks
 *
 * @property Company $company
 */
abstract class BaseInvites extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'invites';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Invites|Invites', $n);
	}

	public static function representingColumn() {
		return 'cre_date';
	}

	public function rules() {
		return array(
			array('cre_date, company_id, invite_key', 'required'),
			array('company_id', 'numerical', 'integerOnly'=>true),
			array('username, lastname', 'length', 'max'=>128),
			array('email, remarks', 'length', 'max'=>256),
			array('invite_key', 'length', 'max'=>512),
			array('username, lastname, email, remarks', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, cre_date, company_id, username, lastname, email, invite_key, remarks', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'company' => array(self::BELONGS_TO, 'Company', 'company_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'cre_date' => Yii::t('app', 'Valid Till'),
			'company_id' => null,
			'username' => Yii::t('app', 'Firstname'),
			'lastname' => Yii::t('app', 'Lastname'),
			'email' => Yii::t('app', 'Email'),
			'invite_key' => Yii::t('app', 'Invite Key'),
			'remarks' => Yii::t('app', 'Remarks'),
			'company' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('cre_date', $this->cre_date, true);
		$criteria->compare('company_id', $this->company_id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('invite_key', $this->invite_key, true);
		$criteria->compare('remarks', $this->remarks, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}