<?php

/**
 * This is the model base class for the table "master_locations".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MasterLocations".
 *
 * Columns in table "master_locations" available as properties of the model,
 * followed by relations of table "master_locations" available as properties of the model.
 *
 * @property integer $id
 * @property string $location_address
 * @property string $location_no
 * @property string $location_zipcode
 * @property string $location_city
 * @property string $remarks
 *
 * @property CompanyLocation[] $companyLocations
 * @property LocationSchedule[] $locationSchedules
 */
abstract class BaseMasterLocations extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'master_locations';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'MasterLocations|MasterLocations', $n);
	}

	public static function representingColumn() {
		return 'location_address';
	}

	public function rules() {
		return array(
			array('location_address, location_zipcode, location_city', 'required'),
			array('location_address, location_city', 'length', 'max'=>256),
			array('location_no, location_zipcode', 'length', 'max'=>32),
			array('remarks', 'length', 'max'=>512),
			array('location_no, remarks', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, location_address, location_no, location_zipcode, location_city, remarks', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'companyLocations' => array(self::HAS_MANY, 'CompanyLocation', 'location_id'),
			'locationSchedules' => array(self::HAS_MANY, 'LocationSchedule', 'loc_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'location_address' => Yii::t('app', 'Street & No'),
			'location_no' => Yii::t('app', 'Location No'),
			'location_zipcode' => Yii::t('app', 'Zipcode'),
			'location_city' => Yii::t('app', 'City'),
			'remarks' => Yii::t('app', 'Remarks'),
			'companyLocations' => null,
			'locationSchedules' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('location_address', $this->location_address, true);
		$criteria->compare('location_no', $this->location_no, true);
		$criteria->compare('location_zipcode', $this->location_zipcode, true);
		$criteria->compare('location_city', $this->location_city, true);
		$criteria->compare('remarks', $this->remarks, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}