<?php

/**
 * This is the model base class for the table "orders".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Orders".
 *
 * Columns in table "orders" available as properties of the model,
 * followed by relations of table "orders" available as properties of the model.
 *
 * @property integer $id
 * @property string $user_id
 * @property string $order_date
 * @property integer $plan_id
 * @property string $status
 *
 * @property User $user
 */
abstract class BaseOrders extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'orders';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Orders|Orders', $n);
	}

	public static function representingColumn() {
		return 'order_date';
	}

	public function rules() {
		return array(
			array('user_id, order_date, plan_id', 'required'),
			array('plan_id', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>11),
			array('status', 'length', 'max'=>128),
			array('status', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, order_date, plan_id, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'order_date' => Yii::t('app', 'Order Date'),
			'plan_id' => Yii::t('app', 'Plan'),
			'status' => Yii::t('app', 'Status'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('order_date', $this->order_date, true);
		$criteria->compare('plan_id', $this->plan_id);
		$criteria->compare('status', $this->status, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}