<?php

/**
 * This is the model base class for the table "profile".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProfileModel".
 *
 * Columns in table "profile" available as properties of the model,
 * followed by relations of table "profile" available as properties of the model.
 *
 * @property string $id
 * @property string $user_id
 * @property string $timestamp
 * @property string $privacy
 * @property string $lastname
 * @property string $firstname
 * @property integer $show_friends
 * @property integer $allow_comments
 * @property string $email
 * @property string $street
 * @property string $city
 * @property string $about
 * @property string $initials
 * @property string $telephone_work
 * @property string $telephone_private
 * @property string $address_zipcode
 * @property string $company_name
 * @property string $company_address
 * @property string $company_zipcode
 * @property string $company_city
 * @property string $car_make
 * @property string $car_model
 * @property string $car_color
 * @property integer $car_type
 * @property string $car_lease_company
 * @property string $car_number_plate
 * @property integer $company_id
 * @property integer $location_id
 * @property string $bank_account
 * @property string $profile_complete_status
 * @property string $country
 * @property string $bank_name
 *
 * @property User $user
 */
abstract class BaseProfileModel extends GxActiveRecord {
	public $_username;
	public $_status ;
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'profile';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProfileModel|ProfileModels', $n);
	}

	public static function representingColumn() {
		return 'firstname';
	}

	public function rules() {
		return array(
			array('user_id, timestamp, privacy', 'required'),
			array('show_friends, allow_comments, car_type, company_id, location_id', 'numerical', 'integerOnly'=>true),
			array('user_id', 'length', 'max'=>10),
			array('privacy', 'length', 'max'=>9),
			array('lastname, firstname, initials, car_lease_company', 'length', 'max'=>50),
			array('email, street, city, company_city, car_make, car_model', 'length', 'max'=>255),
			array('telephone_work, telephone_private', 'length', 'max'=>20),
			array('address_zipcode, company_zipcode', 'length', 'max'=>15),
			array('company_name, company_address', 'length', 'max'=>200),
			array('car_color, bank_account, bank_name', 'length', 'max'=>128),
			array('car_number_plate, profile_complete_status, country', 'length', 'max'=>32),
			array('about', 'safe'),
			array('lastname, firstname, show_friends, allow_comments, email, street, city, about, initials, telephone_work, telephone_private, address_zipcode, company_name, company_address, company_zipcode, company_city, car_make, car_model, car_color, car_type, car_lease_company, car_number_plate, company_id, location_id, bank_account, profile_complete_status, country, bank_name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user_id, timestamp, privacy, lastname, firstname, show_friends, allow_comments, email, street, city, about, initials, telephone_work, telephone_private, address_zipcode, company_name, company_address, company_zipcode, company_city, car_make, car_model, car_color, car_type, car_lease_company, car_number_plate, company_id, location_id, bank_account, profile_complete_status, country, bank_name, username, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'user' => array(self::BELONGS_TO, 'UserModel', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user_id' => null,
			'timestamp' => Yii::t('app', 'Timestamp'),
			'privacy' => Yii::t('app', 'Privacy'),
			'lastname' => Yii::t('app', 'Lastname'),
			'firstname' => Yii::t('app', 'Firstname'),
			'show_friends' => Yii::t('app', 'Show Friends'),
			'allow_comments' => Yii::t('app', 'Allow Comments'),
			'email' => Yii::t('app', 'Email'),
			'street' => Yii::t('app', 'Street'),
			'city' => Yii::t('app', 'City'),
			'about' => Yii::t('app', 'About'),
			'initials' => Yii::t('app', 'Initials'),
			'telephone_work' => Yii::t('app', 'Telephone Work'),
			'telephone_private' => Yii::t('app', 'Telephone Private'),
			'address_zipcode' => Yii::t('app', 'Address Zipcode'),
			'company_name' => Yii::t('app', 'Company Name'),
			'company_address' => Yii::t('app', 'Company Address'),
			'company_zipcode' => Yii::t('app', 'Company Zipcode'),
			'company_city' => Yii::t('app', 'Company City'),
			'car_make' => Yii::t('app', 'Car Make'),
			'car_model' => Yii::t('app', 'Car Model'),
			'car_color' => Yii::t('app', 'Car Color'),
			'car_type' => Yii::t('app', 'Car Type'),
			'car_lease_company' => Yii::t('app', 'Car Lease Company'),
			'car_number_plate' => Yii::t('app', 'Car Number Plate'),
			'company_id' => Yii::t('app', 'Company'),
			'location_id' => Yii::t('app', 'Location'),
			'bank_account' => Yii::t('app', 'Bank Account'),
			'profile_complete_status' => Yii::t('app', 'Profile Complete Status'),
			'country' => Yii::t('app', 'Country'),
			'bank_name' => Yii::t('app', 'Bank Name'),
			'user' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;
		$criteria->with = 'user' ;
		$criteria->compare('id', $this->id, true);
		$criteria->compare('user_id', $this->user_id);
		$criteria->compare('timestamp', $this->timestamp, true);
		$criteria->compare('privacy', $this->privacy, true);
		$criteria->compare('lastname', $this->lastname, true);
		$criteria->compare('firstname', $this->firstname, true);
		$criteria->compare('show_friends', $this->show_friends);
		$criteria->compare('allow_comments', $this->allow_comments);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('street', $this->street, true);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('about', $this->about, true);
		$criteria->compare('initials', $this->initials, true);
		$criteria->compare('telephone_work', $this->telephone_work, true);
		$criteria->compare('telephone_private', $this->telephone_private, true);
		$criteria->compare('address_zipcode', $this->address_zipcode, true);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('company_address', $this->company_address, true);
		$criteria->compare('company_zipcode', $this->company_zipcode, true);
		$criteria->compare('company_city', $this->company_city, true);
		$criteria->compare('car_make', $this->car_make, true);
		$criteria->compare('car_model', $this->car_model, true);
		$criteria->compare('car_color', $this->car_color, true);
		$criteria->compare('car_type', $this->car_type);
		$criteria->compare('car_lease_company', $this->car_lease_company, true);
		$criteria->compare('car_number_plate', $this->car_number_plate, true);
		$criteria->compare('company_id', $this->company_id);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('bank_account', $this->bank_account, true);
		$criteria->compare('profile_complete_status', $this->profile_complete_status, true);
		$criteria->compare('country', $this->country, true);
		$criteria->compare('bank_name', $this->bank_name, true);
		$criteria->compare('user.username', $this->_username, true);
		$criteria->compare('user.status', $this->_status, true);
		$sort = new CSort();
		$sort->attributes = array(
			'defaultOrder'=>'firstname ASC',
    'status'=>array(
        'asc'=>'user.status',
        'desc'=>'user.status desc',
    ),
    'firstname'=>array(
    	'asc'=>'firstname',
    	'desc'=>'firstname desc',
    ),
    'lastname'=>array(
    	'asc'=>'lastname',
    	'desc'=>'lastname desc',
    ),
    'username'=>array(
    	'asc'=>'user.username',
    	'desc'=>'user.username desc',
    ),
    'email'=>array(
    	'asc'=>'email',
    	'desc'=>'email desc',
    ),
		);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
			'sort'=>$sort ,
		));
	}
	public function getUsername(){
		if ($this->_username === null && $this->user !== null) {
    	    $this->_username = $this->user->username;
    	}
	    return $this->_username;
	}
	public function setUsername($value){
		$this->_username = $value ;
	}
	public function getStatus(){
		if ($this->_status === null && $this->user !== null) {
    	    $this->_status = $this->user->status;
    	}
	    return $this->_status;
	}
	public function setStatus($value){
		$this->_status = $value ;
	}
}