<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserModel".
 *
 * Columns in table "user" available as properties of the model,
 * followed by relations of table "user" available as properties of the model.
 *
 * @property string $id
 * @property string $username
 * @property string $password
 * @property string $salt
 * @property string $activationKey
 * @property integer $createtime
 * @property integer $lastvisit
 * @property integer $lastaction
 * @property integer $lastpasswordchange
 * @property integer $superuser
 * @property integer $status
 * @property string $avatar
 * @property string $notifyType
 *
 * @property Orders[] $orders
 * @property Profile[] $profiles
 * @property Reservations[] $reservations
 * @property Subscription[] $subscriptions
 */
abstract class BaseUserModel extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserModel|UserModels', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password, salt', 'required'),
			array('createtime, lastvisit, lastaction, lastpasswordchange, superuser, status', 'numerical', 'integerOnly'=>true),
			array('username', 'length', 'max'=>20),
			array('password, salt, activationKey', 'length', 'max'=>128),
			array('avatar', 'length', 'max'=>255),
			array('notifyType', 'length', 'max'=>9),
			array('activationKey, createtime, lastvisit, lastaction, lastpasswordchange, superuser, status, avatar, notifyType', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, password, salt, activationKey, createtime, lastvisit, lastaction, lastpasswordchange, superuser, status, avatar, notifyType', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'orders' => array(self::HAS_MANY, 'Orders', 'user_id'),
			'profiles' => array(self::HAS_ONE, 'ProfileModel', 'user_id'),
			'reservations' => array(self::HAS_MANY, 'Reservations', 'user_id'),
			'subscriptions' => array(self::HAS_MANY, 'Subscription', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'salt' => Yii::t('app', 'Salt'),
			'activationKey' => Yii::t('app', 'Activation Key'),
			'createtime' => Yii::t('app', 'Createtime'),
			'lastvisit' => Yii::t('app', 'Lastvisit'),
			'lastaction' => Yii::t('app', 'Lastaction'),
			'lastpasswordchange' => Yii::t('app', 'Lastpasswordchange'),
			'superuser' => Yii::t('app', 'Superuser'),
			'status' => Yii::t('app', 'Status'),
			'avatar' => Yii::t('app', 'Avatar'),
			'notifyType' => Yii::t('app', 'Notify Type'),
			'orders' => null,
			'profiles' => null,
			'reservations' => null,
			'subscriptions' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('salt', $this->salt, true);
		$criteria->compare('activationKey', $this->activationKey, true);
		$criteria->compare('createtime', $this->createtime);
		$criteria->compare('lastvisit', $this->lastvisit);
		$criteria->compare('lastaction', $this->lastaction);
		$criteria->compare('lastpasswordchange', $this->lastpasswordchange);
		$criteria->compare('superuser', $this->superuser);
		$criteria->compare('status', $this->status);
		$criteria->compare('avatar', $this->avatar, true);
		$criteria->compare('notifyType', $this->notifyType, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}